extends Node

## Database de personagens jogaveis.

var characters: Dictionary = {
	"amazona": {
		"name": "Amazona",
		"starting_weapon": "crossbow",
		"passive": "+15% velocidade + 10% dano com lancas",
		"color": Color(0.85, 0.55, 0.2),
		"speed_bonus": 0.15,
		"damage_bonus": 0.10,
	},
	"bruxa": {
		"name": "Moon Witch",
		"starting_weapon": "necro",
		"passive": "+2 invocacoes extras, summons 20% mais fortes",
		"color": Color(0.45, 0.15, 0.55),
		"speed_bonus": 0.0,
		"damage_bonus": 0.0,
		"summon_bonus": 2,
		"summon_damage_bonus": 0.20,
	},
	"lealith": {
		"name": "Lealith",
		"starting_weapon": "scythe",
		"passive": "+25% velocidade, +15% dodge, -15% HP max",
		"color": Color(0.15, 0.3, 0.85),
		"speed_bonus": 0.25,
		"damage_bonus": 0.0,
		"dodge_bonus": 0.15,
		"hp_mult": -0.15,
	},
	"ronin": {
		"name": "Ronin",
		"starting_weapon": "scythe",
		"passive": "+20% critical hit, +10% dano",
		"color": Color(0.2, 0.85, 0.3),
		"speed_bonus": 0.0,
		"damage_bonus": 0.0,
	},
	"soldado": {
		"name": "Soldado",
		"starting_weapon": "machinegun",
		"passive": "+15% attack speed",
		"color": Color(0.3, 0.5, 0.9),
		"speed_bonus": 0.0,
		"damage_bonus": 0.0,
		"attack_speed_bonus": 0.15,
	},
	"mago": {
		"name": "Mago",
		"starting_weapon": "staff",
		"passive": "+25% area de efeito",
		"color": Color(0.7, 0.3, 0.9),
		"speed_bonus": 0.0,
		"damage_bonus": 0.0,
		"area_bonus": 0.25,
	},
	"berserker": {
		"name": "Berserker",
		"starting_weapon": "axe",
		"passive": "+30% dano quando HP < 40%",
		"color": Color(0.8, 0.2, 0.1),
		"speed_bonus": 0.0,
		"damage_bonus": 0.0,
		"low_hp_damage_bonus": 0.30,
		"unlock_condition": "total_kills",
		"unlock_value": 1000,
		"unlock_description": "Mate 1000 inimigos no total",
	},
	"ninja": {
		"name": "Ninja",
		"starting_weapon": "scythe",
		"passive": "+20% velocidade, +10% dodge",
		"color": Color(0.1, 0.1, 0.1),
		"speed_bonus": 0.20,
		"damage_bonus": 0.0,
		"dodge_bonus": 0.10,
		"unlock_condition": "complete_stage",
		"unlock_value": "cemetery",
		"unlock_description": "Complete o Cemiterio",
	},
	"pirata": {
		"name": "Pirata",
		"starting_weapon": "dual_pistol",
		"passive": "+20% drop de cristais, +10% dano",
		"color": Color(0.6, 0.4, 0.2),
		"speed_bonus": 0.0,
		"damage_bonus": 0.0,
		"unlock_condition": "complete_stage",
		"unlock_value": "forest",
		"unlock_description": "Complete a Floresta Encantada",
	},
	"engenheiro": {
		"name": "Engenheiro",
		"starting_weapon": "drone",
		"passive": "+15% cooldown reduction",
		"color": Color(0.9, 0.7, 0.2),
		"speed_bonus": 0.0,
		"damage_bonus": 0.0,
		"unlock_condition": "complete_stage",
		"unlock_value": "cemetery",
		"unlock_description": "Complete o Cemiterio",
	},
	"vampiro": {
		"name": "Vampiro",
		"starting_weapon": "blood_orb",
		"passive": "Lifesteal 3%",
		"color": Color(0.5, 0.0, 0.1),
		"speed_bonus": 0.0,
		"damage_bonus": 0.0,
		"unlock_condition": "complete_stage",
		"unlock_value": "forest",
		"unlock_description": "Complete a Floresta Encantada",
	},
	"gladiador": {
		"name": "Gladiador",
		"starting_weapon": "crossbow",
		"passive": "+20% armadura",
		"color": Color(0.8, 0.65, 0.2),
		"speed_bonus": 0.0,
		"damage_bonus": 0.0,
		"unlock_condition": "complete_stage",
		"unlock_value": "cemetery",
		"unlock_description": "Complete o Cemiterio",
	},
	"chef": {
		"name": "Chef",
		"starting_weapon": "axe",
		"passive": "Cura 2x efetiva",
		"color": Color(1.0, 0.95, 0.9),
		"speed_bonus": 0.0,
		"damage_bonus": 0.0,
		"unlock_condition": "complete_stage",
		"unlock_value": "forest",
		"unlock_description": "Complete a Floresta Encantada",
	},
	"mystery": {
		"name": "???",
		"starting_weapon": "scythe",
		"passive": "Todas as armas nivel 1",
		"color": Color(0.5, 0.5, 0.5),
		"speed_bonus": 0.0,
		"damage_bonus": 0.0,
		"unlock_condition": "all_characters",
		"unlock_value": "",
		"unlock_description": "Desbloqueie todos os outros personagens",
	},
	"fragmentado": {
		"name": "Fragmentado",
		"starting_weapon": "blood_orb",
		"passive": "+10% todos os stats, comeca com 50% HP",
		"color": Color(0.0, 1.0, 0.6),
		"speed_bonus": 0.10,
		"damage_bonus": 0.10,
		"area_bonus": 0.10,
		"unlock_condition": "all_stages",
		"unlock_description": "Complete todas as 10 fases",
	},
}

func get_character(id: String) -> Dictionary:
	if id in characters:
		return characters[id]
	return {}

func get_all_character_ids() -> Array:
	return characters.keys()
