extends Node

## Database de armas. Define stats base e scaling por level.

var weapons: Dictionary = {
	"katana": {
		"name": "Espada Samurai",
		"type": "melee",
		"element": "physical",
		"description": "Corte rapido em arco na frente",
		"base_damage": 15,
		"base_cooldown": 0.8,
		"base_area": 2.0,
		"damage_per_level": 4,
		"cooldown_per_level": -0.06,
		"area_per_level": 0.2,
	},
	"staff": {
		"name": "Staff Magico",
		"type": "ranged",
		"element": "ice",
		"description": "Projetil homing que persegue inimigos",
		"base_damage": 12,
		"base_cooldown": 1.5,
		"base_speed": 12.0,
		"damage_per_level": 4,
		"cooldown_per_level": -0.1,
		"projectiles_per_level": 0,
	},
	"scythe": {
		"name": "Foice",
		"type": "melee",
		"element": "dark",
		"description": "Gira ao redor do jogador, drena vida",
		"base_damage": 10,
		"base_cooldown": 0.0,
		"base_area": 2.5,
		"damage_per_level": 3,
		"cooldown_per_level": 0,
		"area_per_level": 0.3,
		"lifesteal": 0.02,
	},
	"machinegun": {
		"name": "Metralhadora",
		"type": "ranged",
		"element": "electric",
		"description": "Spray de projeteis rapidos",
		"base_damage": 6,
		"base_cooldown": 0.15,
		"base_speed": 20.0,
		"damage_per_level": 2,
		"cooldown_per_level": -0.01,
		"spread": 0.3,
	},
	"bazooka": {
		"name": "Bazuca",
		"type": "ranged",
		"element": "fire",
		"description": "Explosao em area, cooldown longo",
		"base_damage": 30,
		"base_cooldown": 3.5,
		"base_speed": 10.0,
		"base_area": 3.0,
		"damage_per_level": 10,
		"cooldown_per_level": -0.2,
		"area_per_level": 0.4,
	},
	"necro": {
		"name": "Necromante",
		"type": "summon",
		"element": "dark",
		"description": "Invoca esqueletos que lutam por voce",
		"base_damage": 6,
		"base_cooldown": 4.0,
		"max_summons": 2,
		"damage_per_level": 2,
		"cooldown_per_level": -0.3,
		"summons_per_level": 1,
	},
	"axe": {
		"name": "Machado Viking",
		"type": "ranged",
		"element": "fire",
		"description": "Machado boomerang que vai e volta",
		"base_damage": 18,
		"base_cooldown": 2.0,
		"base_area": 1.5,
		"damage_per_level": 5,
		"cooldown_per_level": -0.15,
		"area_per_level": 0.2,
	},
	"shadow_claw": {
		"name": "Shadow Claw",
		"type": "melee",
		"element": "shadow",
		"description": "Garras sombrias com duplo corte rapido",
		"base_damage": 12,
		"base_cooldown": 0.7,
		"base_area": 1.3,
		"damage_per_level": 4,
		"cooldown_per_level": -0.05,
		"area_per_level": 0.15,
	},
	"drone": {
		"name": "Drone",
		"type": "summon",
		"element": "electric",
		"description": "Torrinha orbitante que dispara no inimigo mais proximo",
		"base_damage": 10,
		"base_cooldown": 1.5,
		"base_area": 2.0,
		"damage_per_level": 4,
		"cooldown_per_level": -0.1,
		"area_per_level": 0.1,
	},
	"totem": {
		"name": "Totem Eletrico",
		"type": "summon",
		"element": "electric",
		"description": "Planta um totem que causa dano em area",
		"base_damage": 14,
		"base_cooldown": 5.0,
		"base_area": 4.0,
		"damage_per_level": 4,
		"cooldown_per_level": -0.3,
		"area_per_level": 0.5,
		"max_summons": 1,
		"summons_per_level": 0,
	},
	"poison_bottle": {
		"name": "Garrafa de Veneno",
		"type": "ranged",
		"element": "poison",
		"description": "Arremessa garrafas que criam pocas de veneno",
		"base_damage": 8,
		"base_cooldown": 2.5,
		"base_area": 2.0,
		"damage_per_level": 3,
		"cooldown_per_level": -0.15,
		"area_per_level": 0.3,
	},
	"lightning_chain": {
		"name": "Relampago em Cadeia",
		"type": "summon",
		"element": "electric",
		"description": "Raio que encadeia entre inimigos proximos",
		"base_damage": 12,
		"base_cooldown": 2.0,
		"damage_per_level": 4,
		"cooldown_per_level": -0.12,
		"chains_per_level": 1,
	},
	"magic_book": {
		"name": "Livro Magico",
		"type": "melee",
		"element": "physical",
		"description": "Orbita o jogador e dispara paginas cortantes",
		"base_damage": 8,
		"base_cooldown": 0.0,
		"base_area": 1.5,
		"damage_per_level": 3,
		"cooldown_per_level": 0,
		"area_per_level": 0.1,
	},
	"whip": {
		"name": "Chicote",
		"type": "melee",
		"element": "physical",
		"description": "Chicotada em arco de 180 graus, passa por todos os inimigos",
		"base_damage": 12,
		"base_cooldown": 0.9,
		"base_area": 3.0,
		"damage_per_level": 4,
		"cooldown_per_level": -0.07,
		"area_per_level": 0.25,
	},
	"lance": {
		"name": "Lanca",
		"type": "melee",
		"element": "physical",
		"description": "Investida em linha reta, perfura multiplos inimigos",
		"base_damage": 18,
		"base_cooldown": 1.0,
		"base_area": 4.0,
		"damage_per_level": 5,
		"cooldown_per_level": -0.06,
		"area_per_level": 0.3,
	},
	"hammer": {
		"name": "Martelo",
		"type": "melee",
		"element": "physical",
		"description": "Slam no chao com shockwave em area",
		"base_damage": 25,
		"base_cooldown": 2.0,
		"base_area": 3.0,
		"damage_per_level": 8,
		"cooldown_per_level": -0.12,
		"area_per_level": 0.3,
	},
	"nunchaku": {
		"name": "Nunchaku",
		"type": "melee",
		"element": "physical",
		"description": "Ataque rapido em cone, velocidade aumenta com level",
		"base_damage": 8,
		"base_cooldown": 0.5,
		"base_area": 1.5,
		"damage_per_level": 3,
		"cooldown_per_level": -0.04,
		"area_per_level": 0.15,
	},
	"dual_katana": {
		"name": "Katana Dupla",
		"type": "melee",
		"element": "physical",
		"description": "Dois cortes simultaneos em X",
		"base_damage": 12,
		"base_cooldown": 0.85,
		"base_area": 2.0,
		"damage_per_level": 4,
		"cooldown_per_level": -0.07,
		"area_per_level": 0.2,
	},
	"dual_pistol": {
		"name": "Pistola Dupla",
		"type": "ranged",
		"element": "physical",
		"description": "Tiros alternados rapidos esquerda-direita",
		"base_damage": 5,
		"base_cooldown": 0.18,
		"base_speed": 24.0,
		"damage_per_level": 2,
		"cooldown_per_level": -0.01,
		"spread": 0.15,
	},
	"flamethrower": {
		"name": "Lancachamas",
		"type": "ranged",
		"element": "fire",
		"description": "Cone de fogo continuo na direcao do inimigo",
		"base_damage": 8,
		"base_cooldown": 2.5,
		"base_area": 2.5,
		"damage_per_level": 3,
		"cooldown_per_level": -0.15,
		"area_per_level": 0.3,
		# Disabled: flamethrower requires manual aiming (cone direction),
		# but the game uses auto-aim only. Keep disabled until manual aim is supported.
		"disabled": true,
	},
	"ice_staff": {
		"name": "Cajado de Gelo",
		"type": "ranged",
		"element": "ice",
		"description": "Projetil lento que congela inimigos em area ao impactar",
		"base_damage": 14,
		"base_cooldown": 2.0,
		"base_speed": 10.0,
		"base_area": 3.0,
		"damage_per_level": 4,
		"cooldown_per_level": -0.12,
		"area_per_level": 0.3,
	},
	"crossbow": {
		"name": "Crossbow",
		"type": "ranged",
		"element": "physical",
		"description": "Tiro unico de alto dano que perfura todos os inimigos",
		"base_damage": 22,
		"base_cooldown": 1.8,
		"base_speed": 28.0,
		"damage_per_level": 7,
		"cooldown_per_level": -0.1,
	},
	"plasma_cannon": {
		"name": "Plasma Cannon",
		"type": "ranged",
		"element": "electric",
		"description": "Carrega e dispara um feixe devastador de plasma",
		"base_damage": 40,
		"base_cooldown": 5.0,
		"base_area": 2.0,
		"damage_per_level": 12,
		"cooldown_per_level": -0.3,
		"area_per_level": 0.25,
	},
	"cloud_sword": {
		"name": "Espada Cloud",
		"type": "melee",
		"element": "physical",
		"description": "Golpe frontal massivo em arco de 180 graus",
		"base_damage": 35,
		"base_cooldown": 2.0,
		"base_area": 3.0,
		"damage_per_level": 10,
		"cooldown_per_level": -0.12,
		"area_per_level": 0.3,
	},
	"elven_bow": {
		"name": "Arco Elfico",
		"type": "ranged",
		"element": "physical",
		"description": "Flecha perfurante que ricocheta uma vez",
		"base_damage": 14,
		"base_cooldown": 1.2,
		"base_speed": 20.0,
		"damage_per_level": 4,
		"cooldown_per_level": -0.08,
		"projectiles_per_level": 0,
	},
	"boxing_gloves": {
		"name": "Luvas de Boxe",
		"type": "melee",
		"element": "physical",
		"description": "Combo rapido de 3 hits com knockback forte",
		"base_damage": 20,
		"base_cooldown": 1.5,
		"base_area": 1.5,
		"damage_per_level": 6,
		"cooldown_per_level": -0.1,
		"area_per_level": 0.15,
	},
	"time_bomb": {
		"name": "Bomba Relogio",
		"type": "summon",
		"element": "fire",
		"description": "Dropa bomba que explode apos 3 segundos",
		"base_damage": 28,
		"base_cooldown": 4.0,
		"base_area": 4.0,
		"damage_per_level": 8,
		"cooldown_per_level": -0.2,
		"area_per_level": 0.4,
		"max_summons": 3,
		"summons_per_level": 0,
	},
	"portal_weapon": {
		"name": "Portal",
		"type": "summon",
		"element": "dark",
		"description": "Teleporta clusters de inimigos para longe",
		"base_damage": 12,
		"base_cooldown": 5.0,
		"base_area": 3.0,
		"damage_per_level": 5,
		"cooldown_per_level": -0.25,
		"area_per_level": 0.3,
	},
	"boomerang": {
		"name": "Boomerang",
		"type": "ranged",
		"element": "physical",
		"description": "Vai e volta, perfura inimigos na ida",
		"base_damage": 16,
		"base_cooldown": 1.5,
		"base_speed": 15.0,
		"damage_per_level": 5,
		"cooldown_per_level": -0.1,
	},
	"tornado": {
		"name": "Tornado",
		"type": "summon",
		"element": "ice",
		"description": "Vortex giratorio que puxa inimigos proximos",
		"base_damage": 6,
		"base_cooldown": 6.0,
		"base_area": 5.0,
		"damage_per_level": 2,
		"cooldown_per_level": -0.3,
		"area_per_level": 0.5,
		"max_summons": 1,
		"summons_per_level": 0,
	},
	"chain_whip": {
		"name": "Chicote Eletrico",
		"type": "melee",
		"element": "electric",
		"description": "Chicote que chains entre inimigos proximos",
		"base_damage": 10,
		"base_cooldown": 1.0,
		"base_area": 3.5,
		"damage_per_level": 3,
		"cooldown_per_level": -0.07,
		"area_per_level": 0.3,
	},
	"blood_orb": {
		"name": "Orbe de Sangue",
		"type": "summon",
		"element": "dark",
		"description": "Orbe que drena vida dos inimigos proximos",
		"base_damage": 4,
		"base_cooldown": 5.0,
		"base_area": 4.0,
		"damage_per_level": 2,
		"cooldown_per_level": -0.25,
		"area_per_level": 0.4,
		"max_summons": 1,
		"summons_per_level": 0,
		"lifesteal": 0.05,
	},
}

func get_weapon(id: String) -> Dictionary:
	if id in weapons:
		return weapons[id]
	return {}

func get_damage(id: String, level: int) -> float:
	var w = get_weapon(id)
	if w.is_empty():
		return 0
	return w["base_damage"] + w["damage_per_level"] * (level - 1)

func get_cooldown(id: String, level: int) -> float:
	var w = get_weapon(id)
	if w.is_empty():
		return 1.0
	return maxf(0.05, w["base_cooldown"] + w["cooldown_per_level"] * (level - 1))

func get_element(id: String) -> String:
	var w = get_weapon(id)
	return w.get("element", "physical")

func get_all_weapon_ids() -> Array:
	return weapons.keys()
